# This file was autogenerated from vk-api json schema

from typing import List, Union, Optional, overload
from easy_vk.types import objects
from easy_vk.types import responses
from easy_vk.api_category import BaseCategory
try:
    from typing import Literal
except Exception:
    from typing_extensions import Literal


class Appwidgets(BaseCategory):
    def update(self, code: str, type_: str) -> responses.BaseOk:
        """
        Allows to update community app widget

        :param code:
        :param type_:
        """

        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        param_aliases = [('type_', 'type')]
        method_name = 'appWidgets.update'
        response_type = responses.BaseOk
        return self._call(method_name, method_parameters, param_aliases, response_type)
