# This file was autogenerated from vk-api json schema

from pydantic import BaseModel, Field
from typing import List, Union, Optional, NewType
from enum import Enum
from . import responses


class AccountBanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountChangePasswordModel(BaseModel):
    response: Optional[responses.AccountChangePassword] = Field(None)


class AccountGetActiveOffersModel(BaseModel):
    response: Optional[responses.AccountGetActiveOffers] = Field(None)


class AccountGetAppPermissionsModel(BaseModel):
    response: Optional[responses.AccountGetAppPermissions] = Field(None)


class AccountGetBannedModel(BaseModel):
    response: Optional[responses.AccountGetBanned] = Field(None)


class AccountGetCountersModel(BaseModel):
    response: Optional[responses.AccountGetCounters] = Field(None)


class AccountGetInfoModel(BaseModel):
    response: Optional[responses.AccountGetInfo] = Field(None)


class AccountGetProfileInfoModel(BaseModel):
    response: Optional[responses.AccountGetProfileInfo] = Field(None)


class AccountGetPushSettingsModel(BaseModel):
    response: Optional[responses.AccountGetPushSettings] = Field(None)


class AccountRegisterDeviceModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSaveProfileInfoModel(BaseModel):
    response: Optional[responses.AccountSaveProfileInfo] = Field(None)


class AccountSetInfoModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSetNameInMenuModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSetOfflineModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSetOnlineModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSetPushSettingsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountSetSilenceModeModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountUnbanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AccountUnregisterDeviceModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AdsAddOfficeUsersModel(BaseModel):
    response: Optional[responses.AdsAddOfficeUsers] = Field(None)


class AdsCheckLinkModel(BaseModel):
    response: Optional[responses.AdsCheckLink] = Field(None)


class AdsCreateAdsModel(BaseModel):
    response: Optional[responses.AdsCreateAds] = Field(None)


class AdsCreateCampaignsModel(BaseModel):
    response: Optional[responses.AdsCreateCampaigns] = Field(None)


class AdsCreateClientsModel(BaseModel):
    response: Optional[responses.AdsCreateClients] = Field(None)


class AdsCreateTargetGroupModel(BaseModel):
    response: Optional[responses.AdsCreateTargetGroup] = Field(None)


class AdsDeleteAdsModel(BaseModel):
    response: Optional[responses.AdsDeleteAds] = Field(None)


class AdsDeleteCampaignsModel(BaseModel):
    response: Optional[responses.AdsDeleteCampaigns] = Field(None)


class AdsDeleteClientsModel(BaseModel):
    response: Optional[responses.AdsDeleteClients] = Field(None)


class AdsDeleteTargetGroupModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AdsGetAccountsModel(BaseModel):
    response: Optional[responses.AdsGetAccounts] = Field(None)


class AdsGetAdsModel(BaseModel):
    response: Optional[responses.AdsGetAds] = Field(None)


class AdsGetAdsLayoutModel(BaseModel):
    response: Optional[responses.AdsGetAdsLayout] = Field(None)


class AdsGetAdsTargetingModel(BaseModel):
    response: Optional[responses.AdsGetAdsTargeting] = Field(None)


class AdsGetBudgetModel(BaseModel):
    response: Optional[responses.AdsGetBudget] = Field(None)


class AdsGetCampaignsModel(BaseModel):
    response: Optional[responses.AdsGetCampaigns] = Field(None)


class AdsGetCategoriesModel(BaseModel):
    response: Optional[responses.AdsGetCategories] = Field(None)


class AdsGetClientsModel(BaseModel):
    response: Optional[responses.AdsGetClients] = Field(None)


class AdsGetDemographicsModel(BaseModel):
    response: Optional[responses.AdsGetDemographics] = Field(None)


class AdsGetFloodStatsModel(BaseModel):
    response: Optional[responses.AdsGetFloodStats] = Field(None)


class AdsGetLookalikeRequestsModel(BaseModel):
    response: Optional[responses.AdsGetLookalikeRequests] = Field(None)


class AdsGetMusiciansModel(BaseModel):
    response: Optional[responses.AdsGetMusicians] = Field(None)


class AdsGetOfficeUsersModel(BaseModel):
    response: Optional[responses.AdsGetOfficeUsers] = Field(None)


class AdsGetPostsReachModel(BaseModel):
    response: Optional[responses.AdsGetPostsReach] = Field(None)


class AdsGetRejectionReasonModel(BaseModel):
    response: Optional[responses.AdsGetRejectionReason] = Field(None)


class AdsGetStatisticsModel(BaseModel):
    response: Optional[responses.AdsGetStatistics] = Field(None)


class AdsGetSuggestionsModel(BaseModel):
    response: Optional[Union[responses.AdsGetSuggestions, responses.AdsGetSuggestionsRegions, responses.AdsGetSuggestionsCities, responses.AdsGetSuggestionsSchools]] = Field(None)


class AdsGetTargetGroupsModel(BaseModel):
    response: Optional[responses.AdsGetTargetGroups] = Field(None)


class AdsGetTargetingStatsModel(BaseModel):
    response: Optional[responses.AdsGetTargetingStats] = Field(None)


class AdsGetUploadURLModel(BaseModel):
    response: Optional[responses.AdsGetUploadUrl] = Field(None)


class AdsGetVideoUploadURLModel(BaseModel):
    response: Optional[responses.AdsGetVideoUploadUrl] = Field(None)


class AdsImportTargetContactsModel(BaseModel):
    response: Optional[responses.AdsImportTargetContacts] = Field(None)


class AdsRemoveOfficeUsersModel(BaseModel):
    response: Optional[responses.AdsRemoveOfficeUsers] = Field(None)


class AdsUpdateAdsModel(BaseModel):
    response: Optional[responses.AdsUpdateAds] = Field(None)


class AdsUpdateCampaignsModel(BaseModel):
    response: Optional[responses.AdsUpdateCampaigns] = Field(None)


class AdsUpdateClientsModel(BaseModel):
    response: Optional[responses.AdsUpdateClients] = Field(None)


class AdsUpdateTargetGroupModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AppwidgetsUpdateModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AppsDeleteAppRequestsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AppsGetModel(BaseModel):
    response: Optional[responses.AppsGet] = Field(None)


class AppsGetCatalogModel(BaseModel):
    response: Optional[responses.AppsGetCatalog] = Field(None)


class AppsGetFriendsListModel(BaseModel):
    response: Optional[responses.AppsGetFriendsList] = Field(None)


class AppsGetLeaderboardModel(BaseModel):
    response: Optional[Union[responses.AppsGetLeaderboard, responses.AppsGetLeaderboardExtended]] = Field(None)


class AppsGetScopesModel(BaseModel):
    response: Optional[responses.AppsGetScopes] = Field(None)


class AppsGetScoreModel(BaseModel):
    response: Optional[responses.AppsGetScore] = Field(None)


class AppsPromoHasActiveGiftModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class AppsPromoUseGiftModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class AppsSendRequestModel(BaseModel):
    response: Optional[responses.AppsSendRequest] = Field(None)


class AuthCheckPhoneModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class AuthRestoreModel(BaseModel):
    response: Optional[responses.AuthRestore] = Field(None)


class BoardAddTopicModel(BaseModel):
    response: Optional[responses.BoardAddTopic] = Field(None)


class BoardCloseTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardCreateCommentModel(BaseModel):
    response: Optional[responses.BoardCreateComment] = Field(None)


class BoardDeleteCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardDeleteTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardEditTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardFixTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardGetCommentsModel(BaseModel):
    response: Optional[Union[responses.BoardGetComments, responses.BoardGetCommentsExtended]] = Field(None)


class BoardGetTopicsModel(BaseModel):
    response: Optional[Union[responses.BoardGetTopics, responses.BoardGetTopicsExtended]] = Field(None)


class BoardOpenTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardRestoreCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class BoardUnfixTopicModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class DatabaseGetChairsModel(BaseModel):
    response: Optional[responses.DatabaseGetChairs] = Field(None)


class DatabaseGetCitiesModel(BaseModel):
    response: Optional[responses.DatabaseGetCities] = Field(None)


class DatabaseGetCitiesByIdModel(BaseModel):
    response: Optional[responses.DatabaseGetCitiesById] = Field(None)


class DatabaseGetCountriesModel(BaseModel):
    response: Optional[responses.DatabaseGetCountries] = Field(None)


class DatabaseGetCountriesByIdModel(BaseModel):
    response: Optional[responses.DatabaseGetCountriesById] = Field(None)


class DatabaseGetFacultiesModel(BaseModel):
    response: Optional[responses.DatabaseGetFaculties] = Field(None)


class DatabaseGetMetroStationsModel(BaseModel):
    response: Optional[responses.DatabaseGetMetroStations] = Field(None)


class DatabaseGetMetroStationsByIdModel(BaseModel):
    response: Optional[responses.DatabaseGetMetroStationsById] = Field(None)


class DatabaseGetRegionsModel(BaseModel):
    response: Optional[responses.DatabaseGetRegions] = Field(None)


class DatabaseGetSchoolClassesModel(BaseModel):
    response: Optional[responses.DatabaseGetSchoolClasses] = Field(None)


class DatabaseGetSchoolsModel(BaseModel):
    response: Optional[responses.DatabaseGetSchools] = Field(None)


class DatabaseGetUniversitiesModel(BaseModel):
    response: Optional[responses.DatabaseGetUniversities] = Field(None)


class DocsAddModel(BaseModel):
    response: Optional[responses.DocsAdd] = Field(None)


class DocsDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class DocsEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class DocsGetModel(BaseModel):
    response: Optional[responses.DocsGet] = Field(None)


class DocsGetByIdModel(BaseModel):
    response: Optional[responses.DocsGetById] = Field(None)


class DocsGetMessagesUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class DocsGetTypesModel(BaseModel):
    response: Optional[responses.DocsGetTypes] = Field(None)


class DocsGetUploadServerModel(BaseModel):
    response: Optional[responses.DocsGetUploadServer] = Field(None)


class DocsGetWallUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class DocsSaveModel(BaseModel):
    response: Optional[responses.DocsSave] = Field(None)


class DocsSearchModel(BaseModel):
    response: Optional[responses.DocsSearch] = Field(None)


class DownloadedgamesGetPaidStatusModel(BaseModel):
    response: Optional[responses.DownloadedGamesPaidStatus] = Field(None)


class FaveAddArticleModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveAddLinkModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveAddPageModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveAddPostModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveAddProductModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveAddTagModel(BaseModel):
    response: Optional[responses.FaveAddTag] = Field(None)


class FaveAddVideoModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveEditTagModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveGetModel(BaseModel):
    response: Optional[Union[responses.FaveGet, responses.FaveGetExtended]] = Field(None)


class FaveGetPagesModel(BaseModel):
    response: Optional[responses.FaveGetPages] = Field(None)


class FaveGetTagsModel(BaseModel):
    response: Optional[responses.FaveGetTags] = Field(None)


class FaveMarkSeenModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class FaveRemoveArticleModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class FaveRemoveLinkModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveRemovePageModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveRemovePostModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveRemoveProductModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveRemoveTagModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveReorderTagsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveSetPageTagsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveSetTagsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FaveTrackPageInteractionModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FriendsAddModel(BaseModel):
    response: Optional[responses.FriendsAdd] = Field(None)


class FriendsAddListModel(BaseModel):
    response: Optional[responses.FriendsAddList] = Field(None)


class FriendsAreFriendsModel(BaseModel):
    response: Optional[Union[responses.FriendsAreFriends, responses.FriendsAreFriendsExtended]] = Field(None)


class FriendsDeleteModel(BaseModel):
    response: Optional[responses.FriendsDelete] = Field(None)


class FriendsDeleteAllRequestsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FriendsDeleteListModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FriendsEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FriendsEditListModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class FriendsGetModel(BaseModel):
    response: Optional[Union[responses.FriendsGet, responses.FriendsGetFields]] = Field(None)


class FriendsGetAppUsersModel(BaseModel):
    response: Optional[responses.FriendsGetAppUsers] = Field(None)


class FriendsGetByPhonesModel(BaseModel):
    response: Optional[responses.FriendsGetByPhones] = Field(None)


class FriendsGetListsModel(BaseModel):
    response: Optional[responses.FriendsGetLists] = Field(None)


class FriendsGetMutualModel(BaseModel):
    response: Optional[Union[responses.FriendsGetMutual, responses.FriendsGetMutualTargetUids]] = Field(None)


class FriendsGetOnlineModel(BaseModel):
    response: Optional[Union[responses.FriendsGetOnline, responses.FriendsGetOnlineOnlineMobile]] = Field(None)


class FriendsGetRecentModel(BaseModel):
    response: Optional[responses.FriendsGetRecent] = Field(None)


class FriendsGetRequestsModel(BaseModel):
    response: Optional[Union[responses.FriendsGetRequests, responses.FriendsGetRequestsNeedMutual, responses.FriendsGetRequestsExtended]] = Field(None)


class FriendsGetSuggestionsModel(BaseModel):
    response: Optional[responses.FriendsGetSuggestions] = Field(None)


class FriendsSearchModel(BaseModel):
    response: Optional[responses.FriendsSearch] = Field(None)


class GiftsGetModel(BaseModel):
    response: Optional[responses.GiftsGet] = Field(None)


class GroupsAddAddressModel(BaseModel):
    response: Optional[responses.GroupsAddAddress] = Field(None)


class GroupsAddCallbackServerModel(BaseModel):
    response: Optional[responses.GroupsAddCallbackServer] = Field(None)


class GroupsAddLinkModel(BaseModel):
    response: Optional[responses.GroupsAddLink] = Field(None)


class GroupsApproveRequestModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsBanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsCreateModel(BaseModel):
    response: Optional[responses.GroupsCreate] = Field(None)


class GroupsDeleteCallbackServerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsDeleteLinkModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsDisableOnlineModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsEditAddressModel(BaseModel):
    response: Optional[responses.GroupsEditAddress] = Field(None)


class GroupsEditCallbackServerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsEditLinkModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsEditManagerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsEnableOnlineModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsGetModel(BaseModel):
    response: Optional[Union[responses.GroupsGet, responses.GroupsGetExtended]] = Field(None)


class GroupsGetAddressesModel(BaseModel):
    response: Optional[responses.GroupsGetAddresses] = Field(None)


class GroupsGetBannedModel(BaseModel):
    response: Optional[responses.GroupsGetBanned] = Field(None)


class GroupsGetByIdModel(BaseModel):
    response: Optional[responses.GroupsGetById] = Field(None)


class GroupsGetCallbackConfirmationCodeModel(BaseModel):
    response: Optional[responses.GroupsGetCallbackConfirmationCode] = Field(None)


class GroupsGetCallbackServersModel(BaseModel):
    response: Optional[responses.GroupsGetCallbackServers] = Field(None)


class GroupsGetCallbackSettingsModel(BaseModel):
    response: Optional[responses.GroupsGetCallbackSettings] = Field(None)


class GroupsGetCatalogModel(BaseModel):
    response: Optional[responses.GroupsGetCatalog] = Field(None)


class GroupsGetCatalogInfoModel(BaseModel):
    response: Optional[Union[responses.GroupsGetCatalogInfo, responses.GroupsGetCatalogInfoExtended]] = Field(None)


class GroupsGetInvitedUsersModel(BaseModel):
    response: Optional[responses.GroupsGetInvitedUsers] = Field(None)


class GroupsGetInvitesModel(BaseModel):
    response: Optional[Union[responses.GroupsGetInvites, responses.GroupsGetInvitesExtended]] = Field(None)


class GroupsGetLongPollServerModel(BaseModel):
    response: Optional[responses.GroupsGetLongPollServer] = Field(None)


class GroupsGetLongPollSettingsModel(BaseModel):
    response: Optional[responses.GroupsGetLongPollSettings] = Field(None)


class GroupsGetMembersModel(BaseModel):
    response: Optional[Union[responses.GroupsGetMembers, responses.GroupsGetMembersFields, responses.GroupsGetMembersFilter]] = Field(None)


class GroupsGetRequestsModel(BaseModel):
    response: Optional[Union[responses.GroupsGetRequests, responses.GroupsGetRequestsFields]] = Field(None)


class GroupsGetSettingsModel(BaseModel):
    response: Optional[responses.GroupsGetSettings] = Field(None)


class GroupsGetTokenPermissionsModel(BaseModel):
    response: Optional[responses.GroupsGetTokenPermissions] = Field(None)


class GroupsInviteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsIsMemberModel(BaseModel):
    response: Optional[Union[responses.GroupsIsMember, responses.GroupsIsMemberUserIds, responses.GroupsIsMemberExtended, responses.GroupsIsMemberUserIdsExtended]] = Field(None)


class GroupsJoinModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsLeaveModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsRemoveUserModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsReorderLinkModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsSearchModel(BaseModel):
    response: Optional[responses.GroupsSearch] = Field(None)


class GroupsSetCallbackSettingsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsSetLongPollSettingsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class GroupsUnbanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class LeadsCheckUserModel(BaseModel):
    response: Optional[responses.LeadsCheckUser] = Field(None)


class LeadsCompleteModel(BaseModel):
    response: Optional[responses.LeadsComplete] = Field(None)


class LeadsGetStatsModel(BaseModel):
    response: Optional[responses.LeadsGetStats] = Field(None)


class LeadsGetUsersModel(BaseModel):
    response: Optional[responses.LeadsGetUsers] = Field(None)


class LeadsMetricHitModel(BaseModel):
    response: Optional[responses.LeadsMetricHit] = Field(None)


class LeadsStartModel(BaseModel):
    response: Optional[responses.LeadsStart] = Field(None)


class LikesAddModel(BaseModel):
    response: Optional[responses.LikesAdd] = Field(None)


class LikesDeleteModel(BaseModel):
    response: Optional[responses.LikesDelete] = Field(None)


class LikesGetListModel(BaseModel):
    response: Optional[Union[responses.LikesGetList, responses.LikesGetListExtended]] = Field(None)


class LikesIsLikedModel(BaseModel):
    response: Optional[responses.LikesIsLiked] = Field(None)


class MarketAddModel(BaseModel):
    response: Optional[responses.MarketAdd] = Field(None)


class MarketAddAlbumModel(BaseModel):
    response: Optional[responses.MarketAddAlbum] = Field(None)


class MarketAddToAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketCreateCommentModel(BaseModel):
    response: Optional[responses.MarketCreateComment] = Field(None)


class MarketDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketDeleteAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketDeleteCommentModel(BaseModel):
    response: Optional[responses.MarketDeleteComment] = Field(None)


class MarketEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketEditAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketGetModel(BaseModel):
    response: Optional[Union[responses.MarketGet, responses.MarketGetExtended]] = Field(None)


class MarketGetAlbumByIdModel(BaseModel):
    response: Optional[responses.MarketGetAlbumById] = Field(None)


class MarketGetAlbumsModel(BaseModel):
    response: Optional[responses.MarketGetAlbums] = Field(None)


class MarketGetByIdModel(BaseModel):
    response: Optional[Union[responses.MarketGetById, responses.MarketGetByIdExtended]] = Field(None)


class MarketGetCategoriesModel(BaseModel):
    response: Optional[responses.MarketGetCategories] = Field(None)


class MarketGetCommentsModel(BaseModel):
    response: Optional[responses.MarketGetComments] = Field(None)


class MarketRemoveFromAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketReorderAlbumsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketReorderItemsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketReportModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketReportCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketRestoreModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MarketRestoreCommentModel(BaseModel):
    response: Optional[responses.MarketRestoreComment] = Field(None)


class MarketSearchModel(BaseModel):
    response: Optional[Union[responses.MarketSearch, responses.MarketSearchExtended]] = Field(None)


class MessagesAddChatUserModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesAllowMessagesFromGroupModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesCreateChatModel(BaseModel):
    response: Optional[responses.MessagesCreateChat] = Field(None)


class MessagesDeleteModel(BaseModel):
    response: Optional[responses.MessagesDelete] = Field(None)


class MessagesDeleteChatPhotoModel(BaseModel):
    response: Optional[responses.MessagesDeleteChatPhoto] = Field(None)


class MessagesDeleteConversationModel(BaseModel):
    response: Optional[responses.MessagesDeleteConversation] = Field(None)


class MessagesDenyMessagesFromGroupModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesEditModel(BaseModel):
    response: Optional[responses.MessagesEdit] = Field(None)


class MessagesEditChatModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesGetByConversationMessageIdModel(BaseModel):
    response: Optional[responses.MessagesGetByConversationMessageId] = Field(None)


class MessagesGetByIdModel(BaseModel):
    response: Optional[Union[responses.MessagesGetById, responses.MessagesGetByIdExtended]] = Field(None)


class MessagesGetChatPreviewModel(BaseModel):
    response: Optional[responses.MessagesGetChatPreview] = Field(None)


class MessagesGetConversationMembersModel(BaseModel):
    response: Optional[responses.MessagesGetConversationMembers] = Field(None)


class MessagesGetConversationsModel(BaseModel):
    response: Optional[responses.MessagesGetConversations] = Field(None)


class MessagesGetConversationsByIdModel(BaseModel):
    response: Optional[Union[responses.MessagesGetConversationsById, responses.MessagesGetConversationsByIdExtended]] = Field(None)


class MessagesGetHistoryModel(BaseModel):
    response: Optional[responses.MessagesGetHistory] = Field(None)


class MessagesGetHistoryAttachmentsModel(BaseModel):
    response: Optional[responses.MessagesGetHistoryAttachments] = Field(None)


class MessagesGetInviteLinkModel(BaseModel):
    response: Optional[responses.MessagesGetInviteLink] = Field(None)


class MessagesGetLastActivityModel(BaseModel):
    response: Optional[responses.MessagesGetLastActivity] = Field(None)


class MessagesGetLongPollHistoryModel(BaseModel):
    response: Optional[responses.MessagesGetLongPollHistory] = Field(None)


class MessagesGetLongPollServerModel(BaseModel):
    response: Optional[responses.MessagesGetLongPollServer] = Field(None)


class MessagesIsMessagesFromGroupAllowedModel(BaseModel):
    response: Optional[responses.MessagesIsMessagesFromGroupAllowed] = Field(None)


class MessagesJoinChatByInviteLinkModel(BaseModel):
    response: Optional[responses.MessagesJoinChatByInviteLink] = Field(None)


class MessagesMarkAsAnsweredConversationModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesMarkAsImportantModel(BaseModel):
    response: Optional[responses.MessagesMarkAsImportant] = Field(None)


class MessagesMarkAsImportantConversationModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesMarkAsReadModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesPinModel(BaseModel):
    response: Optional[responses.MessagesPin] = Field(None)


class MessagesRemoveChatUserModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesRestoreModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesSearchModel(BaseModel):
    response: Optional[responses.MessagesSearch] = Field(None)


class MessagesSearchConversationsModel(BaseModel):
    response: Optional[responses.MessagesSearchConversations] = Field(None)


class MessagesSendModel(BaseModel):
    response: Optional[Union[responses.MessagesSend, responses.MessagesSendUserIds]] = Field(None)


class MessagesSendMessageEventAnswerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesSetActivityModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class MessagesSetChatPhotoModel(BaseModel):
    response: Optional[responses.MessagesSetChatPhoto] = Field(None)


class MessagesUnpinModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedAddBanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedDeleteBanModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedDeleteListModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedGetModel(BaseModel):
    response: Optional[responses.NewsfeedGet] = Field(None)


class NewsfeedGetBannedModel(BaseModel):
    response: Optional[Union[responses.NewsfeedGetBanned, responses.NewsfeedGetBannedExtended]] = Field(None)


class NewsfeedGetCommentsModel(BaseModel):
    response: Optional[responses.NewsfeedGetComments] = Field(None)


class NewsfeedGetListsModel(BaseModel):
    response: Optional[Union[responses.NewsfeedGetLists, responses.NewsfeedGetListsExtended]] = Field(None)


class NewsfeedGetMentionsModel(BaseModel):
    response: Optional[responses.NewsfeedGetMentions] = Field(None)


class NewsfeedGetRecommendedModel(BaseModel):
    response: Optional[responses.NewsfeedGetRecommended] = Field(None)


class NewsfeedGetSuggestedSourcesModel(BaseModel):
    response: Optional[responses.NewsfeedGetSuggestedSources] = Field(None)


class NewsfeedIgnoreItemModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedSaveListModel(BaseModel):
    response: Optional[responses.NewsfeedSaveList] = Field(None)


class NewsfeedSearchModel(BaseModel):
    response: Optional[Union[responses.NewsfeedSearch, responses.NewsfeedSearchExtended]] = Field(None)


class NewsfeedUnignoreItemModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NewsfeedUnsubscribeModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotesAddModel(BaseModel):
    response: Optional[responses.NotesAdd] = Field(None)


class NotesCreateCommentModel(BaseModel):
    response: Optional[responses.NotesCreateComment] = Field(None)


class NotesDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotesDeleteCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotesEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotesEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotesGetModel(BaseModel):
    response: Optional[responses.NotesGet] = Field(None)


class NotesGetByIdModel(BaseModel):
    response: Optional[responses.NotesGetById] = Field(None)


class NotesGetCommentsModel(BaseModel):
    response: Optional[responses.NotesGetComments] = Field(None)


class NotesRestoreCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class NotificationsGetModel(BaseModel):
    response: Optional[responses.NotificationsGet] = Field(None)


class NotificationsMarkAsViewedModel(BaseModel):
    response: Optional[responses.NotificationsMarkAsViewed] = Field(None)


class NotificationsSendMessageModel(BaseModel):
    response: Optional[responses.NotificationsSendMessage] = Field(None)


class OrdersCancelSubscriptionModel(BaseModel):
    response: Optional[responses.OrdersCancelSubscription] = Field(None)


class OrdersChangeStateModel(BaseModel):
    response: Optional[responses.OrdersChangeState] = Field(None)


class OrdersGetModel(BaseModel):
    response: Optional[responses.OrdersGet] = Field(None)


class OrdersGetAmountModel(BaseModel):
    response: Optional[responses.OrdersGetAmount] = Field(None)


class OrdersGetByIdModel(BaseModel):
    response: Optional[responses.OrdersGetById] = Field(None)


class OrdersGetUserSubscriptionByIdModel(BaseModel):
    response: Optional[responses.OrdersGetUserSubscriptionById] = Field(None)


class OrdersGetUserSubscriptionsModel(BaseModel):
    response: Optional[responses.OrdersGetUserSubscriptions] = Field(None)


class OrdersUpdateSubscriptionModel(BaseModel):
    response: Optional[responses.OrdersUpdateSubscription] = Field(None)


class PagesClearCacheModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PagesGetModel(BaseModel):
    response: Optional[responses.PagesGet] = Field(None)


class PagesGetHistoryModel(BaseModel):
    response: Optional[responses.PagesGetHistory] = Field(None)


class PagesGetTitlesModel(BaseModel):
    response: Optional[responses.PagesGetTitles] = Field(None)


class PagesGetVersionModel(BaseModel):
    response: Optional[responses.PagesGetVersion] = Field(None)


class PagesParseWikiModel(BaseModel):
    response: Optional[responses.PagesParseWiki] = Field(None)


class PagesSaveModel(BaseModel):
    response: Optional[responses.PagesSave] = Field(None)


class PagesSaveAccessModel(BaseModel):
    response: Optional[responses.PagesSaveAccess] = Field(None)


class PhotosConfirmTagModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosCopyModel(BaseModel):
    response: Optional[responses.PhotosCopy] = Field(None)


class PhotosCreateAlbumModel(BaseModel):
    response: Optional[responses.PhotosCreateAlbum] = Field(None)


class PhotosCreateCommentModel(BaseModel):
    response: Optional[responses.PhotosCreateComment] = Field(None)


class PhotosDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosDeleteAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosDeleteCommentModel(BaseModel):
    response: Optional[responses.PhotosDeleteComment] = Field(None)


class PhotosEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosEditAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosGetModel(BaseModel):
    response: Optional[Union[responses.PhotosGet, responses.PhotosGetExtended]] = Field(None)


class PhotosGetAlbumsModel(BaseModel):
    response: Optional[responses.PhotosGetAlbums] = Field(None)


class PhotosGetAlbumsCountModel(BaseModel):
    response: Optional[responses.PhotosGetAlbumsCount] = Field(None)


class PhotosGetAllModel(BaseModel):
    response: Optional[Union[responses.PhotosGetAll, responses.PhotosGetAllExtended]] = Field(None)


class PhotosGetAllCommentsModel(BaseModel):
    response: Optional[responses.PhotosGetAllComments] = Field(None)


class PhotosGetByIdModel(BaseModel):
    response: Optional[Union[responses.PhotosGetById, responses.PhotosGetByIdExtended]] = Field(None)


class PhotosGetChatUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class PhotosGetCommentsModel(BaseModel):
    response: Optional[Union[responses.PhotosGetComments, responses.PhotosGetCommentsExtended]] = Field(None)


class PhotosGetMarketAlbumUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class PhotosGetMarketUploadServerModel(BaseModel):
    response: Optional[responses.PhotosGetMarketUploadServer] = Field(None)


class PhotosGetMessagesUploadServerModel(BaseModel):
    response: Optional[responses.PhotosGetMessagesUploadServer] = Field(None)


class PhotosGetNewTagsModel(BaseModel):
    response: Optional[responses.PhotosGetNewTags] = Field(None)


class PhotosGetOwnerCoverPhotoUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class PhotosGetOwnerPhotoUploadServerModel(BaseModel):
    response: Optional[responses.BaseGetUploadServer] = Field(None)


class PhotosGetTagsModel(BaseModel):
    response: Optional[responses.PhotosGetTags] = Field(None)


class PhotosGetUploadServerModel(BaseModel):
    response: Optional[responses.PhotosGetUploadServer] = Field(None)


class PhotosGetUserPhotosModel(BaseModel):
    response: Optional[Union[responses.PhotosGetUserPhotos, responses.PhotosGetUserPhotosExtended]] = Field(None)


class PhotosGetWallUploadServerModel(BaseModel):
    response: Optional[responses.PhotosGetWallUploadServer] = Field(None)


class PhotosMakeCoverModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosMoveModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosPutTagModel(BaseModel):
    response: Optional[responses.PhotosPutTag] = Field(None)


class PhotosRemoveTagModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosReorderAlbumsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosReorderPhotosModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosReportModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosReportCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosRestoreModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PhotosRestoreCommentModel(BaseModel):
    response: Optional[responses.PhotosRestoreComment] = Field(None)


class PhotosSaveModel(BaseModel):
    response: Optional[responses.PhotosSave] = Field(None)


class PhotosSaveMarketAlbumPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveMarketAlbumPhoto] = Field(None)


class PhotosSaveMarketPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveMarketPhoto] = Field(None)


class PhotosSaveMessagesPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveMessagesPhoto] = Field(None)


class PhotosSaveOwnerCoverPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveOwnerCoverPhoto] = Field(None)


class PhotosSaveOwnerPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveOwnerPhoto] = Field(None)


class PhotosSaveWallPhotoModel(BaseModel):
    response: Optional[responses.PhotosSaveWallPhoto] = Field(None)


class PhotosSearchModel(BaseModel):
    response: Optional[responses.PhotosSearch] = Field(None)


class PollsAddVoteModel(BaseModel):
    response: Optional[responses.PollsAddVote] = Field(None)


class PollsCreateModel(BaseModel):
    response: Optional[responses.PollsCreate] = Field(None)


class PollsDeleteVoteModel(BaseModel):
    response: Optional[responses.PollsDeleteVote] = Field(None)


class PollsEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class PollsGetByIdModel(BaseModel):
    response: Optional[responses.PollsGetById] = Field(None)


class PollsGetVotersModel(BaseModel):
    response: Optional[responses.PollsGetVoters] = Field(None)


class PrettycardsCreateModel(BaseModel):
    response: Optional[responses.PrettyCardsCreate] = Field(None)


class PrettycardsDeleteModel(BaseModel):
    response: Optional[responses.PrettyCardsDelete] = Field(None)


class PrettycardsEditModel(BaseModel):
    response: Optional[responses.PrettyCardsEdit] = Field(None)


class PrettycardsGetModel(BaseModel):
    response: Optional[responses.PrettyCardsGet] = Field(None)


class PrettycardsGetByIdModel(BaseModel):
    response: Optional[responses.PrettyCardsGetById] = Field(None)


class PrettycardsGetUploadURLModel(BaseModel):
    response: Optional[responses.PrettyCardsGetUploadUrl] = Field(None)


class SearchGetHintsModel(BaseModel):
    response: Optional[responses.SearchGetHints] = Field(None)


class SecureAddAppEventModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class SecureCheckTokenModel(BaseModel):
    response: Optional[responses.SecureCheckToken] = Field(None)


class SecureGetAppBalanceModel(BaseModel):
    response: Optional[responses.SecureGetAppBalance] = Field(None)


class SecureGetSMSHistoryModel(BaseModel):
    response: Optional[responses.SecureGetSmshistory] = Field(None)


class SecureGetTransactionsHistoryModel(BaseModel):
    response: Optional[responses.SecureGetTransactionsHistory] = Field(None)


class SecureGetUserLevelModel(BaseModel):
    response: Optional[responses.SecureGetUserLevel] = Field(None)


class SecureGiveEventStickerModel(BaseModel):
    response: Optional[responses.SecureGiveEventSticker] = Field(None)


class SecureSendNotificationModel(BaseModel):
    response: Optional[responses.SecureSendNotification] = Field(None)


class SecureSendSMSNotificationModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class SecureSetCounterModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StatsGetModel(BaseModel):
    response: Optional[responses.StatsGet] = Field(None)


class StatsGetPostReachModel(BaseModel):
    response: Optional[responses.StatsGetPostReach] = Field(None)


class StatsTrackVisitorModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StatusGetModel(BaseModel):
    response: Optional[responses.StatusGet] = Field(None)


class StatusSetModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StorageGetModel(BaseModel):
    response: Optional[Union[responses.StorageGetV5110, responses.StorageGetWithKeys]] = Field(None)


class StorageGetKeysModel(BaseModel):
    response: Optional[responses.StorageGetKeys] = Field(None)


class StorageSetModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StoriesBanOwnerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StoriesDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StoriesGetModel(BaseModel):
    response: Optional[responses.StoriesGetV5113] = Field(None)


class StoriesGetBannedModel(BaseModel):
    response: Optional[Union[responses.StoriesGetBanned, responses.StoriesGetBannedExtended]] = Field(None)


class StoriesGetByIdModel(BaseModel):
    response: Optional[Union[responses.StoriesGetById, responses.StoriesGetByIdExtended]] = Field(None)


class StoriesGetPhotoUploadServerModel(BaseModel):
    response: Optional[responses.StoriesGetPhotoUploadServer] = Field(None)


class StoriesGetRepliesModel(BaseModel):
    response: Optional[responses.StoriesGetV5113] = Field(None)


class StoriesGetStatsModel(BaseModel):
    response: Optional[responses.StoriesGetStats] = Field(None)


class StoriesGetVideoUploadServerModel(BaseModel):
    response: Optional[responses.StoriesGetVideoUploadServer] = Field(None)


class StoriesGetViewersModel(BaseModel):
    response: Optional[Union[responses.StoriesGetViewersExtendedV5115, responses.StoriesGetViewersExtendedV5115]] = Field(None)


class StoriesHideAllRepliesModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StoriesHideReplyModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StoriesSearchModel(BaseModel):
    response: Optional[responses.StoriesGetV5113] = Field(None)


class StoriesUnbanOwnerModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class StreamingGetServerUrlModel(BaseModel):
    response: Optional[responses.StreamingGetServerUrl] = Field(None)


class StreamingSetSettingsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class UsersGetModel(BaseModel):
    response: Optional[responses.UsersGet] = Field(None)


class UsersGetFollowersModel(BaseModel):
    response: Optional[Union[responses.UsersGetFollowers, responses.UsersGetFollowersFields]] = Field(None)


class UsersGetSubscriptionsModel(BaseModel):
    response: Optional[Union[responses.UsersGetSubscriptions, responses.UsersGetSubscriptionsExtended]] = Field(None)


class UsersReportModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class UsersSearchModel(BaseModel):
    response: Optional[responses.UsersSearch] = Field(None)


class UtilsCheckLinkModel(BaseModel):
    response: Optional[responses.UtilsCheckLink] = Field(None)


class UtilsDeleteFromLastShortenedModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class UtilsGetLastShortenedLinksModel(BaseModel):
    response: Optional[responses.UtilsGetLastShortenedLinks] = Field(None)


class UtilsGetLinkStatsModel(BaseModel):
    response: Optional[Union[responses.UtilsGetLinkStats, responses.UtilsGetLinkStatsExtended]] = Field(None)


class UtilsGetServerTimeModel(BaseModel):
    response: Optional[responses.UtilsGetServerTime] = Field(None)


class UtilsGetShortLinkModel(BaseModel):
    response: Optional[responses.UtilsGetShortLink] = Field(None)


class UtilsResolveScreenNameModel(BaseModel):
    response: Optional[responses.UtilsResolveScreenName] = Field(None)


class VideoAddModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoAddAlbumModel(BaseModel):
    response: Optional[responses.VideoAddAlbum] = Field(None)


class VideoAddToAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoCreateCommentModel(BaseModel):
    response: Optional[responses.VideoCreateComment] = Field(None)


class VideoDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoDeleteAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoDeleteCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoEditModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoEditAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoGetModel(BaseModel):
    response: Optional[Union[responses.VideoGet, responses.VideoGetExtended]] = Field(None)


class VideoGetAlbumByIdModel(BaseModel):
    response: Optional[responses.VideoGetAlbumById] = Field(None)


class VideoGetAlbumsModel(BaseModel):
    response: Optional[Union[responses.VideoGetAlbums, responses.VideoGetAlbumsExtended]] = Field(None)


class VideoGetAlbumsByVideoModel(BaseModel):
    response: Optional[Union[responses.VideoGetAlbumsByVideo, responses.VideoGetAlbumsByVideoExtended]] = Field(None)


class VideoGetCommentsModel(BaseModel):
    response: Optional[Union[responses.VideoGetComments, responses.VideoGetCommentsExtended]] = Field(None)


class VideoRemoveFromAlbumModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoReorderAlbumsModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoReorderVideosModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoReportModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoReportCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoRestoreModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class VideoRestoreCommentModel(BaseModel):
    response: Optional[responses.VideoRestoreComment] = Field(None)


class VideoSaveModel(BaseModel):
    response: Optional[responses.VideoSave] = Field(None)


class VideoSearchModel(BaseModel):
    response: Optional[Union[responses.VideoSearch, responses.VideoSearchExtended]] = Field(None)


class WallCloseCommentsModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class WallCreateCommentModel(BaseModel):
    response: Optional[responses.WallCreateComment] = Field(None)


class WallDeleteModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallDeleteCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallEditModel(BaseModel):
    response: Optional[responses.WallEdit] = Field(None)


class WallEditAdsStealthModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallEditCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallGetModel(BaseModel):
    response: Optional[Union[responses.WallGet, responses.WallGetExtended]] = Field(None)


class WallGetByIdModel(BaseModel):
    response: Optional[Union[responses.WallGetById, responses.WallGetByIdExtended]] = Field(None)


class WallGetCommentModel(BaseModel):
    response: Optional[Union[responses.WallGetComment, responses.WallGetCommentExtended]] = Field(None)


class WallGetCommentsModel(BaseModel):
    response: Optional[Union[responses.WallGetComments, responses.WallGetCommentsExtended]] = Field(None)


class WallGetRepostsModel(BaseModel):
    response: Optional[responses.WallGetReposts] = Field(None)


class WallOpenCommentsModel(BaseModel):
    response: Optional[responses.BaseBool] = Field(None)


class WallPinModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallPostModel(BaseModel):
    response: Optional[responses.WallPost] = Field(None)


class WallPostAdsStealthModel(BaseModel):
    response: Optional[responses.WallPostAdsStealth] = Field(None)


class WallReportCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallReportPostModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallRepostModel(BaseModel):
    response: Optional[responses.WallRepost] = Field(None)


class WallRestoreModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallRestoreCommentModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WallSearchModel(BaseModel):
    response: Optional[Union[responses.WallSearch, responses.WallSearchExtended]] = Field(None)


class WallUnpinModel(BaseModel):
    response: Optional[responses.BaseOk] = Field(None)


class WidgetsGetCommentsModel(BaseModel):
    response: Optional[responses.WidgetsGetComments] = Field(None)


class WidgetsGetPagesModel(BaseModel):
    response: Optional[responses.WidgetsGetPages] = Field(None)
