# This file was autogenerated from vk-api json schema

from typing import List, Union, Optional
from easy_vk.types import objects
from easy_vk.types import response_models
from easy_vk.api_category import BaseCategory


class Database(BaseCategory):
    def __init__(self, session, access_token: str, v: str, delay: float, auto_retry: bool, max_retries: int, timeout: float):
        super().__init__(session, access_token, v, delay, auto_retry, max_retries, timeout)

    def get_chairs(self, faculty_id: int = None, offset: int = None, count: int = None) -> response_models.DatabaseGetChairsModel:
        """
        Returns list of chairs on a specified faculty.
        
        :param faculty_id: id of the faculty to get chairs from
        :param offset: offset required to get a certain subset of chairs
        :param count: amount of chairs to get
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getChairs'
        param_aliases = []
        response_type = response_models.DatabaseGetChairsModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_cities(self, country_id: int = None, region_id: int = None, q: str = None, need_all: bool = None, offset: int = None, count: int = None) -> response_models.DatabaseGetCitiesModel:
        """
        Returns a list of cities.
        
        :param country_id: Country ID.
        :param region_id: Region ID.
        :param q: Search query.
        :param need_all: '1' — to return all cities in the country, '0' — to return major cities in the country (default),
        :param offset: Offset needed to return a specific subset of cities.
        :param count: Number of cities to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getCities'
        param_aliases = []
        response_type = response_models.DatabaseGetCitiesModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_cities_by_id(self, city_ids: List[int] = None) -> response_models.DatabaseGetCitiesByIdModel:
        """
        Returns information about cities by their IDs.
        
        :param city_ids: City IDs.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getCitiesById'
        param_aliases = []
        response_type = response_models.DatabaseGetCitiesByIdModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_countries(self, need_all: bool = None, code: str = None, offset: int = None, count: int = None) -> response_models.DatabaseGetCountriesModel:
        """
        Returns a list of countries.
        
        :param need_all: '1' — to return a full list of all countries, '0' — to return a list of countries near the current user's country (default).
        :param code: Country codes in [vk.com/dev/country_codes|ISO 3166-1 alpha-2] standard.
        :param offset: Offset needed to return a specific subset of countries.
        :param count: Number of countries to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getCountries'
        param_aliases = []
        response_type = response_models.DatabaseGetCountriesModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_countries_by_id(self, country_ids: List[int] = None) -> response_models.DatabaseGetCountriesByIdModel:
        """
        Returns information about countries by their IDs.
        
        :param country_ids: Country IDs.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getCountriesById'
        param_aliases = []
        response_type = response_models.DatabaseGetCountriesByIdModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_faculties(self, university_id: int = None, offset: int = None, count: int = None) -> response_models.DatabaseGetFacultiesModel:
        """
        Returns a list of faculties (i.e., university departments).
        
        :param university_id: University ID.
        :param offset: Offset needed to return a specific subset of faculties.
        :param count: Number of faculties to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getFaculties'
        param_aliases = []
        response_type = response_models.DatabaseGetFacultiesModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_metro_stations(self, city_id: int = None, offset: int = None, count: int = None, extended: bool = None) -> response_models.DatabaseGetMetroStationsModel:
        """
        Get metro stations by city
        
        :param city_id: 
        :param offset: 
        :param count: 
        :param extended: 
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getMetroStations'
        param_aliases = []
        response_type = response_models.DatabaseGetMetroStationsModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_metro_stations_by_id(self, station_ids: List[int] = None) -> response_models.DatabaseGetMetroStationsByIdModel:
        """
        Get metro station by his id
        
        :param station_ids: 
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getMetroStationsById'
        param_aliases = []
        response_type = response_models.DatabaseGetMetroStationsByIdModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_regions(self, country_id: int = None, q: str = None, offset: int = None, count: int = None) -> response_models.DatabaseGetRegionsModel:
        """
        Returns a list of regions.
        
        :param country_id: Country ID, received in [vk.com/dev/database.getCountries|database.getCountries] method.
        :param q: Search query.
        :param offset: Offset needed to return specific subset of regions.
        :param count: Number of regions to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getRegions'
        param_aliases = []
        response_type = response_models.DatabaseGetRegionsModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_school_classes(self, country_id: int = None) -> response_models.DatabaseGetSchoolClassesModel:
        """
        Returns a list of school classes specified for the country.
        
        :param country_id: Country ID.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getSchoolClasses'
        param_aliases = []
        response_type = response_models.DatabaseGetSchoolClassesModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_schools(self, q: str = None, city_id: int = None, offset: int = None, count: int = None) -> response_models.DatabaseGetSchoolsModel:
        """
        Returns a list of schools.
        
        :param q: Search query.
        :param city_id: City ID.
        :param offset: Offset needed to return a specific subset of schools.
        :param count: Number of schools to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getSchools'
        param_aliases = []
        response_type = response_models.DatabaseGetSchoolsModel
        return self._call(method_name, method_parameters, param_aliases, response_type)

    def get_universities(self, q: str = None, country_id: int = None, city_id: int = None, offset: int = None, count: int = None) -> response_models.DatabaseGetUniversitiesModel:
        """
        Returns a list of higher education institutions.
        
        :param q: Search query.
        :param country_id: Country ID.
        :param city_id: City ID.
        :param offset: Offset needed to return a specific subset of universities.
        :param count: Number of universities to return.
        """
    
        method_parameters = {k: v for k, v in locals().items() if k not in {'self', 'raw_response'}}
        method_name = 'database.getUniversities'
        param_aliases = []
        response_type = response_models.DatabaseGetUniversitiesModel
        return self._call(method_name, method_parameters, param_aliases, response_type)
